global:
  scrape_interval: 5s

# Alertmanager
alerting:
  alertmanagers:
    - static_configs:
        - targets: ["localhost:9093"]

rule_files:
  - "alerts.rules"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9099"]

  - job_name: "python_exporter"
    static_configs:
      - targets: ["localhost:8000"]
